/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type BlockObject = {
  _type: 'blockObject'
  blockText?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  coverVideo?: string
  mainVideoTitle?: string
  mainVideo?: string
  caseStudyLink?: Slug
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  disci?: Array<
    {
      _key: string
    } & BlockObject
  >
  tag?: Array<string>
  year?: string
  live?: {
    urltitle?: string
    url?: string
  }
  content?: Array<
    | {
        photo?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        caption?: string
        _type: 'singleImage'
        _key: string
      }
    | {
        photoOne?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        photoTwo?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        caption?: string
        _type: 'twoImages'
        _key: string
      }
    | {
        description?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'normal'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        textBlockType?: 'process' | 'direction'
        _type: 'textBlock'
        _key: string
      }
    | {
        processSingleImage?: Array<{
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'processPhoto'
          _key: string
        }>
        twoImages?: Array<{
          processPhotoOne?: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          }
          processPhotoTwo?: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          }
          _type: 'processTwoImage'
          _key: string
        }>
        singleVideo?: {
          videoLink?: string
          caption?: string
        }
        _type: 'process'
        _key: string
      }
    | {
        videoLink?: string
        caption?: string
        _type: 'singleVideo'
        _key: string
      }
    | {
        videoOneLink?: string
        videoTwoLink?: string
        caption?: string
        _type: 'twoVideos'
        _key: string
      }
  >
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  menuItems?: Array<
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'about'
      }
    | {
        title?: string
        url?: string
        _type: 'navLink'
        _key: string
      }
  >
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  favIcon?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bgColor?: Color
  textColor?: Color
  displayLastUpdated?: boolean
}

export type About = {
  _id: string
  _type: 'about'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  aboutImage?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'aboutImageImage'
    _key: string
  }>
  services?: Array<string>
  technicalAbilities?: Array<string>
  pressAndAwards?: Array<{
    title?: string
    link?: string
    _type: 'pressAndAwards'
    _key: string
  }>
}

export type Home = {
  _id: string
  _type: 'home'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  customLogo?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  overview?: {
    text?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    displayText?: boolean
  }
  showcaseProjects?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'project'
  }>
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | BlockObject
  | Project
  | Settings
  | About
  | Home
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | MediaTag
  | Slug
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./sanity/lib/queries.ts
// Variable: homePageQuery
// Query:   *[_type == "home"][0]{    _id,    _updatedAt,    overview{      text,      displayText,    },    customLogo,    showcaseProjects[]->{     ...,      _type,      disci,      tag,      coverImage{        _type,        asset,        "lqip": asset->metadata.lqip,      },      overview,      "slug": slug.current,      title,      year,    },    title,  }
export type HomePageQueryResult = {
  _id: string
  _updatedAt: string
  overview: {
    text: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    displayText: boolean | null
  } | null
  customLogo: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  showcaseProjects: Array<{
    _id: string
    _type: 'project'
    _createdAt: string
    _updatedAt: string
    _rev: string
    title: string | null
    slug: string | null
    coverImage: {
      _type: 'image'
      asset: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      } | null
      lqip: string | null
    } | null
    coverVideo?: string
    mainVideoTitle?: string
    mainVideo?: string
    caseStudyLink?: Slug
    overview: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    disci: Array<
      {
        _key: string
      } & BlockObject
    > | null
    tag: Array<string> | null
    year: string | null
    live?: {
      urltitle?: string
      url?: string
    }
    content?: Array<
      | {
          description?: Array<{
            children?: Array<{
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }>
            style?:
              | 'blockquote'
              | 'h1'
              | 'h2'
              | 'h3'
              | 'h4'
              | 'h5'
              | 'h6'
              | 'normal'
            listItem?: 'bullet' | 'number'
            markDefs?: Array<{
              href?: string
              _type: 'link'
              _key: string
            }>
            level?: number
            _type: 'block'
            _key: string
          }>
          textBlockType?: 'direction' | 'process'
          _type: 'textBlock'
          _key: string
        }
      | {
          photo?: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          }
          caption?: string
          _type: 'singleImage'
          _key: string
        }
      | {
          photoOne?: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          }
          photoTwo?: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          }
          caption?: string
          _type: 'twoImages'
          _key: string
        }
      | {
          processSingleImage?: Array<{
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'processPhoto'
            _key: string
          }>
          twoImages?: Array<{
            processPhotoOne?: {
              asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              }
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
            }
            processPhotoTwo?: {
              asset?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
              }
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
            }
            _type: 'processTwoImage'
            _key: string
          }>
          singleVideo?: {
            videoLink?: string
            caption?: string
          }
          _type: 'process'
          _key: string
        }
      | {
          videoLink?: string
          caption?: string
          _type: 'singleVideo'
          _key: string
        }
      | {
          videoOneLink?: string
          videoTwoLink?: string
          caption?: string
          _type: 'twoVideos'
          _key: string
        }
    >
  }> | null
  title: string | null
} | null
// Variable: moreProjectsQuery
// Query:   *[_type == "home"][0]{    showcaseProjects[]->{      _type,      coverImage{        _type,        asset,        "lqip": asset->metadata.lqip,      },      overview,      "slug": slug.current,      title,      tag,      year,      _updatedAt,    },  }
export type MoreProjectsQueryResult = {
  showcaseProjects: Array<{
    _type: 'project'
    coverImage: {
      _type: 'image'
      asset: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      } | null
      lqip: string | null
    } | null
    overview: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    slug: string | null
    title: string | null
    tag: Array<string> | null
    year: string | null
    _updatedAt: string
  }> | null
} | null
// Variable: aboutPageQuery
// Query:   *[_type == "about"][0]{  ...,    _id,    title,    customLogo,    overview,    aboutImage[]{      _type,      asset,      "lqip": asset->metadata.lqip,    },    aboutLinks[]{      _type,      title,      url,    },    technicalAbilities,    services,    pressAndAwards  }
export type AboutPageQueryResult = {
  _id: string
  _type: 'about'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string | null
  overview: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  aboutImage: Array<{
    _type: 'aboutImageImage'
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    } | null
    lqip: string | null
  }> | null
  services: Array<string> | null
  technicalAbilities: Array<string> | null
  pressAndAwards: Array<{
    title?: string
    link?: string
    _type: 'pressAndAwards'
    _key: string
  }> | null
  customLogo: null
  aboutLinks: null
} | null
// Variable: homePageTitleQuery
// Query:   *[_type == "home"][0].title
export type HomePageTitleQueryResult = string | null
// Variable: projectBySlugQuery
// Query:   *[_type == "project" && slug.current == $slug][0] {    _id,    _type,    year,    coverImage{..., image},    mainVideo,    mainVideoTitle,    description,    tag,    overview,    site,    disci,    "slug": slug.current,    title,    content[]{      _type == 'singleImage' => {        _type,        _key,        photo{          _type,          asset,          "lqip": asset->metadata.lqip,        },        caption,      },      _type == 'twoImages' => {        _type,        _key,        photoOne{          _type,          asset,          "lqip": asset->metadata.lqip,        },        photoTwo{          _type,          asset,          "lqip": asset->metadata.lqip,        },        caption,      },      _type == 'textBlock' => {        _type,        _key,        description,        textBlockType      },      _type == 'singleVideo' => {        _type,        _key,        videoLink,        caption,      },      _type == 'twoVideos' => {        _type,        _key,        videoOneLink,        videoTwoLink,        caption,      },      _type == "process" => {      _type,      ...      }    },  }
export type ProjectBySlugQueryResult = {
  _id: string
  _type: 'project'
  year: string | null
  coverImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    image: null
  } | null
  mainVideo: string | null
  mainVideoTitle: string | null
  description: null
  tag: Array<string> | null
  overview: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  site: null
  disci: Array<
    {
      _key: string
    } & BlockObject
  > | null
  slug: string | null
  title: string | null
  content: Array<
    | {
        _type: 'process'
        processSingleImage?: Array<{
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'processPhoto'
          _key: string
        }>
        twoImages?: Array<{
          processPhotoOne?: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          }
          processPhotoTwo?: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          }
          _type: 'processTwoImage'
          _key: string
        }>
        singleVideo?: {
          videoLink?: string
          caption?: string
        }
      }
    | {
        _type: 'singleImage'
        _key: string
        photo: {
          _type: 'image'
          asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          } | null
          lqip: string | null
        } | null
        caption: string | null
      }
    | {
        _type: 'singleVideo'
        _key: string
        videoLink: string | null
        caption: string | null
      }
    | {
        _type: 'textBlock'
        _key: string
        description: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'blockquote'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }> | null
        textBlockType: 'direction' | 'process' | null
      }
    | {
        _type: 'twoImages'
        _key: string
        photoOne: {
          _type: 'image'
          asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          } | null
          lqip: string | null
        } | null
        photoTwo: {
          _type: 'image'
          asset: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          } | null
          lqip: string | null
        } | null
        caption: string | null
      }
    | {
        _type: 'twoVideos'
        _key: string
        videoOneLink: string | null
        videoTwoLink: string | null
        caption: string | null
      }
  > | null
} | null
// Variable: projectPaths
// Query:   *[_type == "project" && slug.current != null].slug.current
export type ProjectPathsResult = Array<string | null>
// Variable: settingsQuery
// Query:   *[_type == "settings"][0]{    footer,    "menuItems": {      "page": menuItems[_type == 'reference']->{        _type,        "slug": slug.current,        title,        },      "link": menuItems[_type == 'navLink'] {        _type,        title,        url,      },    },    ogImage,    favIcon,    bgColor {      'r': rgb.r,      'g': rgb.g,      'b': rgb.b,    },    textColor {      'r': rgb.r,      'g': rgb.g,      'b': rgb.b,    },    displayLastUpdated,  }
export type SettingsQueryResult = {
  footer: null
  menuItems: {
    page: Array<{
      _type: 'about'
      slug: null
      title: string | null
    }> | null
    link: Array<{
      _type: 'navLink'
      title: string | null
      url: string | null
    }> | null
  }
  ogImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  favIcon: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  bgColor: {
    r: number | null
    g: number | null
    b: number | null
  } | null
  textColor: {
    r: number | null
    g: number | null
    b: number | null
  } | null
  displayLastUpdated: boolean | null
} | null
